# permissions for end users to edit releasercontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releasercontroller-editor-role
rules:
- apiGroups:
  - devops.kubesphere.io
  resources:
  - releasercontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - releasercontrollers/status
  verbs:
  - get
