# permissions for end users to view releasercontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releasercontroller-viewer-role
rules:
- apiGroups:
  - devops.kubesphere.io
  resources:
  - releasercontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - releasercontrollers/status
  verbs:
  - get
